# Generated by Django 5.1.2 on 2024-11-04 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_empleado_estado"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobante",
            name="tipo_comprobante",
            field=models.CharField(
                choices=[("factura", "Factura"), ("ticket", "Ticket")],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "comprobante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventas.comprobante",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.empleado",
                    ),
                ),
            ],
        ),
    ]
