# Generated by Django 5.1.2 on 2024-11-04 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0002_comprobante_tipo_comprobante_venta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carritoproducto",
            old_name="total",
            new_name="subtotal",
        ),
        migrations.AlterField(
            model_name="carritoproducto",
            name="comprobante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="ventas.comprobante",
            ),
        ),
        migrations.AlterField(
            model_name="comprobante",
            name="observacion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
