# Generated by Django 5.1.2 on 2024-11-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0003_rename_total_carritoproducto_subtotal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carritoproducto",
            name="cantidad",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="carritoproducto",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
