# Generated by Django 5.1.2 on 2024-11-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0004_alter_carritoproducto_cantidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comprobante",
            name="total_comprobante",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
