# Generated by Django 5.1.2 on 2024-11-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0005_alter_comprobante_total_comprobante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente_mayorista",
            name="cuit",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="cliente_mayorista",
            name="telefono",
            field=models.PositiveIntegerField(),
        ),
    ]
