# Generated by Django 5.1.2 on 2024-11-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("Administrativo", "Administrativo"),
                            ("Gerente", "Gerente"),
                            ("Vendedor", "Vendedor"),
                        ]
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("cuit", models.CharField(max_length=11, unique=True)),
                ("telefono", models.CharField(max_length=20)),
                ("fecha_nacimiento", models.DateField()),
                ("fecha_ingreso", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Domicilio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=10)),
                ("departamento", models.CharField(blank=True, max_length=100)),
                ("localidad", models.CharField(max_length=100)),
                (
                    "empleado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domicilio",
                        to="usuarios.empleado",
                    ),
                ),
            ],
        ),
    ]
