# Generated by Django 5.1.2 on 2024-11-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=30)),
                ("tipo", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=30)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=6)),
                ("medida", models.CharField(max_length=30)),
                (
                    "punto_de_pedido",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="")),
                ("nombre", models.CharField(max_length=30)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "unidad_medida",
                    models.CharField(
                        choices=[
                            ("unidad", "u."),
                            ("gramo", "gr."),
                            ("kilogramo", "kg."),
                        ],
                        max_length=10,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("stock", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Panaderia", "panaderia"),
                            ("Pasteleria", "pasteleria"),
                        ],
                        max_length=30,
                    ),
                ),
                ("tipo", models.CharField(max_length=30)),
            ],
        ),
    ]
