# Generated by Django 5.1.2 on 2024-11-04 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0003_alter_insumo_medida"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="tipo",
            new_name="subcategoria",
        ),
    ]
