# Generated by Django 5.1.2 on 2024-11-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0004_rename_tipo_producto_subcategoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
