# Generated by Django 5.1.2 on 2024-11-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0005_alter_producto_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insumo",
            name="cantidad",
        ),
        migrations.AddField(
            model_name="insumo",
            name="stock",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
