# Generated by Django 5.1.2 on 2024-11-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0006_remove_insumo_cantidad_insumo_stock"),
        ("proveedores", "0002_pedido_item_pedido_recepcion_item_recepcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="insumos",
            field=models.ManyToManyField(
                blank=True, related_name="proveedor", to="productos.insumo"
            ),
        ),
    ]
