# Generated by Django 5.1.2 on 2024-11-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proveedores", "0003_proveedor_insumos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item_pedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_pedidos",
                to="proveedores.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="fecha_pedido",
            field=models.DateField(auto_now_add=True),
        ),
    ]
