# Generated by Django 5.1.2 on 2024-11-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proveedores", "0004_alter_item_pedido_pedido_alter_pedido_fecha_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recepcion",
            name="fecha_recepcion",
            field=models.DateField(auto_now_add=True),
        ),
    ]
