# Generated by Django 5.1.2 on 2024-11-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proveedores", "0005_alter_recepcion_fecha_recepcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="recepcion",
            name="total_pedido",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
